### ISSUE TITLE
Configure the Redux Store

### ISSUE THREAD

**Issue by Edd-wordd** [Edd-wordd/echoSphere#20]
#### Description
Create and configure the Redux store, integrating `redux-thunk` middleware to support asynchronous actions and setting up the root reducer.

#### Tasks
- [ ] Create a `store.js` file in a new `src/redux` directory.
- [ ] Configure the Redux store with the `createStore` and `applyMiddleware` functions, adding `redux-thunk` as middleware.
- [ ] Set up the root reducer using `combineReducers`, initially with a placeholder reducer.

#### Acceptance Criteria
- A Redux store is configured and includes middleware support for asynchronous actions.
- The project contains a root reducer ready for future reducers to be combined.

#### Labels
`redux`, `configuration`
